

CREATE TABLE "quartos" (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	description TEXT NOT NULL,
	price TEXT NOT NULL,
	created_at DATETIME DEFAULT (CURRENT_TIMESTAMP),
	update_at DATETIME DEFAULT (CURRENT_TIMESTAMP),
	status TEXT
, Image TEXT);

CREATE TABLE ctrl_reserva (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	cpf TEXT NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    room TEXT NOT NULL,
    days TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    status TEXT
);