CREATE TABLE cadastro (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name TEXT (50) NOT NULL,
	email TEXT (70) NOT NULL,
	password TEXT (10) NOT NULL,
	gender TEXT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	update_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	status TEXT
);

CREATE TABLE "quartos" (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	description TEXT NOT NULL,
	price TEXT NOT NULL,
	created_at DATETIME DEFAULT (CURRENT_TIMESTAMP),
	update_at DATETIME DEFAULT (CURRENT_TIMESTAMP),
	status TEXT,
	Image TEXT
);

CREATE TABLE ctrl_reserva (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	cpf TEXT NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    room TEXT NOT NULL,
    days TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    status TEXT
);

CREATE TABLE servicos (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name TEXT NOT NULL,
	description TEXT,
	price TEXT NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	update_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	status TEXT,
	image TEXT
);